### PR TITLE
Improved build process for JSON object

### PR DESCRIPTION
**Pull request by wadahiro**
Hello,

I have made the following improvements:

- Support for value containing strings that need to be escaped, such as CRLF. It had implemented own assembly of JSON strings, but had omitted to take into account the escaping. Therefore, I fixed it to use the JSON library.
- During the build of the JSON string, optimize multiple value checking to use cached schema.
- The Graph API for update was being called for each JSON key, which was inefficient. Therefore, I optimized the JSON build for update by aggregating them into two, one for Azure AD and one for SharePoint Online attributes.

Also, added the following minor bug fix:

- Mandatory checks are not performed before API calling

### CODE REVIEW

**Comment by matusmacik** [comment]
Hello, 
thank you for your contribution.
Would it be possible to rebase the request with the current state of the project and re-test the project with the integration tests that are present?

**Comment by wadahiro** [comment]
> Would it be possible to rebase the request with the current state of the project and re-test the project with the integration tests that are present?

I rebased and run the integration tests, but I noticed the following points that I'm trying to fix. Please wait for this review.

- There is a potential bug where mandatory checks are not performed [here](https://github.com/Evolveum/connector-microsoft-graph-api/blob/7770e3da3c4f8f4e36e0326dd59c812d7f8cbf56/src/main/java/com/evolveum/polygon/connector/msgraphapi/AttributesValidator.java#L28-L33)
- MS Graph API sometimes fails the tests due to insufficient wait time for eventually consistency.

**Comment by wadahiro** [comment]
@matusmacik 

I have added the fixes. And I checked that all tests passed.

image

**Comment by matusmacik** [comment]
Hello,

Great, thank you for the contribution and updates.

**Pull request merged**
